# Generated by Django 2.2.4 on 2022-09-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dojos_Ninjas_Template_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='Desc',
            field=models.CharField(default='NO_VALUE', max_length=255),
            preserve_default=False,
        ),
    ]
