# Generated by Django 2.2.4 on 2022-09-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='no value', max_length=255),
            preserve_default=False,
        ),
    ]
