# Generated by Django 2.2.4 on 2022-10-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
